version: "3.8" # Version for the docker compose
services:
  # Orion is the context broker
  orion:
    image: fiware/orion # Loads this image from Docker Hub
    hostname: orion # Create a hostname to be easier to find the container in the network
    container_name: fiware-orion # Create a container name to be easier to get information for it
    depends_on:
      - mongo-db # Database for persinting eantity information from orion
    networks:
      - default # Users a local network called default
    ports:
      - "1026:1026" # match port 1026 on the machine to the one in the container
    command: -dbhost mongo-db -logLevel DEBUG -noCache
    healthcheck: # check if orion is healthy
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 10s

  # Databases
  mongo-db:
    image: mongo:4.4 # Loads this image from Docker Hub
    hostname: mongo-db # Create a hostname to be easier to find the container in the network
    container_name: db-mongo # Create a container name to be easier to get information for it
    expose:
      - "27017" # Expose this port to the network
    ports:
      - "27017:27017" # match port 27017 on the machine to the one in the container
    networks:
      - default # Users a local network called default
    volumes: # Uses a volume to persit the data in the database
      - mongo-db:/data
    healthcheck: # check if Mongo DB is healthy
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s

  cygnus:
    image: fiware/cygnus-ngsi
    hostname: cygnus
    container_name: fiware-cygnus
    networks:
      - default
    depends_on:
      - mysql-db
    expose:
      - "5050"
      - "5080"
    ports:
      - "5050:5050" # localhost:5050
      - "5080:5080" # localhost:5080
    environment:
      - "CYGNUS_MYSQL_SERVICE_PORT=5050" # Notification Port that Cygnus listens when subcribing to context data changes
      - "CYGNUS_MYSQL_HOST=mysql-db" # Hostname of the MySQL server used to persist historical context data
      - "CYGNUS_MYSQL_PORT=3306" # Port that the MySQL server uses to listen to commands
      - "CYGNUS_MYSQL_USER=root" # Username for the MySQL database user
      - "CYGNUS_MYSQL_PASS=123" # Password for the MySQL database user
      - "CYGNUS_SERVICE_PORT=5050"
      - "CYGNUS_API_PORT=5080" # Port that Cygnus listens on for operational reasons
      - "CYGNUS_LOG_LEVEL=DEBUG" # The logging level for Cygnus
    healthcheck:
      test: curl --fail -s http://localhost:5080/v1/version || exit 1

  mysql-db:
    restart: always
    image: mysql:5.7
    hostname: mysql-db
    container_name: db-mysql
    expose:
      - "3306"
    ports:
      - "3306:3306" # localhost:3306
    networks:
      - default
    environment:
      - "MYSQL_ROOT_PASSWORD=123"
      - "MYSQL_ROOT_HOST=%"
    volumes:
      - mysql-db:/var/lib/mysql

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    depends_on:
      - mysql-db
    ports:
      - "3000:3000"

networks:
  default:

volumes: # Creates a volume to persit the data in the database
  mongo-db: ~
  mysql-db: ~
